### ISSUE TITLE
width + height

### ISSUE THREAD

**Issue by Boco10** [yii2mod/yii2-c3-chart#2]
Hello,

There is an issue with setting these two property.

This is how it working now:
<?php echo \yii2mod\c3\chart\Chart::widget([
    'height' => 100,
    'width' => 100, 
    'options' => [

This is how it should regarding c3 documentation:
<?php echo \yii2mod\c3\chart\Chart::widget([
    'options' => [
            'id' => 'x',
    ],
    'clientOptions' => [
          'size' => [
                    'height' => 100,
                    'width' => 100, 
           ]

http://c3js.org/samples/options_size.html

**Comment by ihorchepurnyi** [comment]
Hi, these properties have been added to simplify the setup size of the widget.
In function getClientOptions() this two properties will be added to the clientOptions array.

**Comment by Boco10** [comment]
Which will not affect the default values.

**Comment by ihorchepurnyi** [comment]
Okey, thanks. I have been modified getClientOptions func, now you can set size for the widget in the following format:

```
 'clientOptions' => [
     'size' => [
           'height'  => 100,
           'width'   => 100, 
    ]
```
- If size not set, then will be applied default size from widget properties.

**Comment by Boco10** [comment]
Since the c3 working with parent width+height, if you don't define it, will use your default set in the Chart.php. I suggest to remove it.

**Comment by ihorchepurnyi** [comment]
Maybe later, we have a lot of projects with this configuration.
